apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTUybXEyPWwkdnlucHd1NzQkMWljdGgtZ149bzAtJmctYmxoKTdva2k1ajQkZCY0K0Ao
  EMAIL_HOST_PASSWORD : ZXhrZW5qbGZrcXR3ZXB0Zw==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  DJANGO_DEBUG: "True"
  EMAIL_BACKEND : "django.core.mail.backends.smtp.EmailBackend"
  EMAIL_HOST : "smtp.gmail.com"
  EMAIL_HOST_USER : "akhinasi95@gmail.com"
  EMAIL_PORT : "587"
  EMAIL_USE_TLS : "True"
  DEFAULT_FROM_EMAIL : "akhinasi95@gmail.com"
